language: java
dist: trusty
jdk: 
  - oraclejdk8

before_install: 
  - sudo add-apt-repository ppa:webupd8team/java
  - sudo apt update
  - sudo apt install oracle-java8-installer

install:
  - ./gradlew generateGrammar

script:
  - ./gradlew test
